

#spring.jackson.serialization.fail-on-empty-beans=false

server:
    port: 8899

spring:
    datasource:
        url: jdbc:mysql://amazon-instance.ckhlaubobvir.us-east-1.rds.amazonaws.com:3306/lms
        username: root
        password: Password
    jackson:
        serialization:
            fail-on-empty-beans: false
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
       
     